# Generated by Django 2.2 on 2020-06-20 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20200620_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mytodolist',
            options={'verbose_name': "Zwg's ToDoList", 'verbose_name_plural': "Zwg's ToDoList"},
        ),
    ]
