# Generated by Django 2.2 on 2020-06-20 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_auto_20200620_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodolist',
            name='contents',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mytodolist',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='mytodolist',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mytodolist',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
